# Generated by Django 5.0 on 2024-01-17 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_information_about_en_information_about_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='address_en',
        ),
        migrations.RemoveField(
            model_name='information',
            name='address_ru',
        ),
    ]
