# Generated by Django 5.0 on 2024-01-24 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
    ]
