# Generated by Django 5.0 on 2024-01-24 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_product_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='title_ru',
        ),
    ]
