# Generated by Django 5.0 on 2024-01-24 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_product_title_en_remove_product_title_ru'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='content_ru',
            new_name='content_az',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='title_ru',
            new_name='title_az',
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='title_ru',
            new_name='title_az',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='title_ru',
            new_name='title_az',
        ),
        migrations.RenameField(
            model_name='information',
            old_name='about_ru',
            new_name='about_az',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description_ru',
            new_name='description_az',
        ),
    ]
